spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hellostudy
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

