spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hellostudy
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true



# 서버가 세션 가지고 있는 시간 (default: 30m)
#server:
#  servlet:
#    session:
#      timeout: 30m
logging:
  level:
    org.hibernate.SQL: debug
